import 'server-only';
import type {WeeklyUpdateInput} from './weekly-update.schemas'; import type {HistoryItem,TeacherGroup,WeeklySession} from './weekly-update.types'; import {toDatabasePayload} from './weekly-update.model'; import {createServerSupabaseClient} from '@/lib/supabase/server';

export async function listAssignedGroups(schoolId:string,profileId:string):Promise<TeacherGroup[]>{const db=await createServerSupabaseClient();const{data,error}=await db.from('groups').select('id,name_en,name_ar,group_teachers!inner(teacher_profile_id),group_memberships(ends_on),sessions(session_date,status)').eq('school_id',schoolId).eq('is_active',true).eq('group_teachers.teacher_profile_id',profileId).order('name_en');if(error)throw error;return(data as unknown as Array<{id:string;name_en:string;name_ar:string|null;group_memberships:Array<{ends_on:string|null}>;sessions:Array<{session_date:string;status:string}>}>).map((row)=>({id:row.id,nameEn:row.name_en,nameAr:row.name_ar,studentCount:row.group_memberships.filter((m)=>m.ends_on===null).length,lastUpdate:row.sessions.filter((s)=>s.status==='SUBMITTED').map((s)=>s.session_date).sort().at(-1)??null}));}
export async function getSchoolTimezone(schoolId:string){const db=await createServerSupabaseClient();const{data,error}=await db.from('schools').select('timezone').eq('id',schoolId).single();if(error)throw error;return data.timezone as string;}

export async function listTeacherHistory(schoolId:string,profileId:string):Promise<HistoryItem[]>{const db=await createServerSupabaseClient();const{data:assignments,error:assignmentError}=await db.from('group_teachers').select('group_id').eq('school_id',schoolId).eq('teacher_profile_id',profileId);if(assignmentError)throw assignmentError;const groupIds=assignments.map((item)=>item.group_id as string);if(groupIds.length===0)return[];const{data,error}=await db.from('sessions').select('id,session_date,submitted_at,groups(name_en,name_ar)').eq('school_id',schoolId).in('group_id',groupIds).eq('status','SUBMITTED').order('session_date',{ascending:false});if(error)throw error;return(data as unknown as Array<{id:string;session_date:string;submitted_at:string|null;groups:{name_en:string;name_ar:string|null}|null}>).flatMap((row)=>row.groups?[{id:row.id,groupNameEn:row.groups.name_en,groupNameAr:row.groups.name_ar,sessionDate:row.session_date,submittedAt:row.submitted_at}]:[]);}

export async function getWeeklySession(schoolId:string,profileId:string,groupId:string,sessionDate:string):Promise<WeeklySession|null>{const db=await createServerSupabaseClient();const{data:group,error:groupError}=await db.from('groups').select('id,name_en,name_ar,group_teachers!inner(teacher_profile_id)').eq('school_id',schoolId).eq('id',groupId).eq('group_teachers.teacher_profile_id',profileId).maybeSingle();if(groupError)throw groupError;if(!group)return null;const{data:memberships,error:memberError}=await db.from('group_memberships').select('students(id,first_name_en,last_name_en,first_name_ar,last_name_ar)').eq('school_id',schoolId).eq('group_id',groupId).lte('starts_on',sessionDate).or(`ends_on.is.null,ends_on.gte.${sessionDate}`);if(memberError)throw memberError;const roster=(memberships as unknown as Array<{students:{id:string;first_name_en:string;last_name_en:string;first_name_ar:string|null;last_name_ar:string|null}|null}>).flatMap(({students})=>students?[{id:students.id,nameEn:`${students.first_name_en} ${students.last_name_en}`,nameAr:students.first_name_ar&&students.last_name_ar?`${students.first_name_ar} ${students.last_name_ar}`:null}]:[]);const{data:session,error:sessionError}=await db.from('sessions').select('id,status,created_by,group_progress(progress_en,progress_ar,default_performance),attendance(student_id,status),student_progress(student_id,performance_override,comment_en,comment_ar)').eq('school_id',schoolId).eq('group_id',groupId).eq('session_date',sessionDate).maybeSingle();if(sessionError)throw sessionError;const g=group as unknown as {id:string;name_en:string;name_ar:string|null};const s=session as unknown as null|{id:string;status:'DRAFT'|'SUBMITTED';created_by:string;group_progress:{progress_en:string|null;progress_ar:string|null;default_performance:WeeklySession['defaultPerformance']}|null;attendance:Array<{student_id:string;status:WeeklySession['attendance'][number]['status']}>;student_progress:Array<{student_id:string;performance_override:WeeklySession['defaultPerformance'];comment_en:string|null;comment_ar:string|null}>};const progress=s?.group_progress;return{id:s?.id??'',groupId:g.id,groupNameEn:g.name_en,groupNameAr:g.name_ar,sessionDate,status:s?.status??'DRAFT',isOwnedDraft:!s||s.created_by===profileId,progressEn:progress?.progress_en??null,progressAr:progress?.progress_ar??null,defaultPerformance:progress?.default_performance??null,roster,attendance:s?.attendance.map((a)=>({studentId:a.student_id,status:a.status}))??[],exceptions:s?.student_progress.map((e)=>({studentId:e.student_id,performanceOverride:e.performance_override,commentEn:e.comment_en,commentAr:e.comment_ar}))??[]};}

export async function getWeeklySessionById(schoolId:string,profileId:string,id:string){const db=await createServerSupabaseClient();const{data,error}=await db.from('sessions').select('group_id,session_date').eq('school_id',schoolId).eq('id',id).maybeSingle();if(error)throw error;if(!data)return null;return getWeeklySession(schoolId,profileId,data.group_id as string,data.session_date as string);}
export async function saveWeeklyUpdate(input:WeeklyUpdateInput){const db=await createServerSupabaseClient();const payload=toDatabasePayload(input.attendance,input.exceptions);const{data,error}=await db.rpc('save_weekly_update',{p_session_id:input.sessionId,p_group_id:input.groupId,p_session_date:input.sessionDate,p_progress_en:input.progressEn??'',p_progress_ar:input.progressAr??'',p_default_performance:input.defaultPerformance,p_attendance:payload.attendance,p_exceptions:payload.exceptions,p_submit:input.intent==='submit'});if(error)throw error;return data as string;}
