export type DashboardGroup={id:string;nameEn:string;nameAr:string|null;submitted:boolean};
type TeachingUpdateContext={teacherId:string;classSubjectId:string;subjectGroupId:string|null};
type TeachingUpdateSubmission=TeachingUpdateContext&{status:'DRAFT'|'SUBMITTED'};
export type DashboardTeachingUpdate=TeachingUpdateContext&{status:'MISSING'|'DRAFT'|'SUBMITTED'};
type AttendanceConflictContext={classSubjectId:string;subjectGroupId:string|null;weekStart:string;studentId:string};
type AttendanceObservation=AttendanceConflictContext&{status:'PRESENT'|'ABSENT'};
export function summarizeReportDelivery(reports:Array<{status:string}>,deliveries:Array<{status:string}>){return{readyReports:reports.filter((r)=>r.status==='READY').length,failedDeliveries:deliveries.filter((d)=>d.status==='FAILED').length};}
export function schoolWeekForDate(localDate:string){const date=new Date(`${localDate}T12:00:00Z`);const daysSinceMonday=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-daysSinceMonday);const start=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+6);return{start,end:date.toISOString().slice(0,10)};}
export function summarizeGroupSubmissions(activeGroups:Array<{id:string;nameEn:string;nameAr:string|null}>,submittedSessions:Array<{group_id:string}>){const submittedIds=new Set(submittedSessions.map((s)=>s.group_id));const groups=activeGroups.map((g)=>({...g,submitted:submittedIds.has(g.id)}));return{submittedCount:groups.filter((g)=>g.submitted).length,groups};}
const teachingUpdateKey=(c:TeachingUpdateContext)=>`${c.teacherId}:${c.classSubjectId}:${c.subjectGroupId??'whole'}`;
export function summarizeTeachingUpdates(expectedContexts:TeachingUpdateContext[],submissions:TeachingUpdateSubmission[]){const expectedByKey=new Map<string,TeachingUpdateContext>();for(const context of expectedContexts){const key=teachingUpdateKey(context);if(!expectedByKey.has(key))expectedByKey.set(key,context);}const submissionByKey=new Map(submissions.map((s)=>[teachingUpdateKey(s),s.status]));const contexts=[...expectedByKey.values()].map((context)=>({...context,status:submissionByKey.get(teachingUpdateKey(context))??'MISSING' as const}));return{expectedCount:contexts.length,submittedCount:contexts.filter(({status})=>status==='SUBMITTED').length,draftCount:contexts.filter(({status})=>status==='DRAFT').length,missingCount:contexts.filter(({status})=>status==='MISSING').length,contexts};}
const attendanceConflictKey=(c:AttendanceConflictContext)=>`${c.classSubjectId}:${c.subjectGroupId??'whole'}:${c.weekStart}:${c.studentId}`;
export function countUnresolvedAttendanceConflicts(observations:AttendanceObservation[],resolutions:AttendanceConflictContext[]){const statusesByKey=new Map<string,Set<'PRESENT'|'ABSENT'>>();for(const observation of observations){const key=attendanceConflictKey(observation);const statuses=statusesByKey.get(key)??new Set<'PRESENT'|'ABSENT'>();statuses.add(observation.status);statusesByKey.set(key,statuses);}const resolvedKeys=new Set(resolutions.map(attendanceConflictKey));return[...statusesByKey.entries()].filter(([key,statuses])=>statuses.size>1&&!resolvedKeys.has(key)).length;}
export function summarizeActionableDashboard({expectedContexts,submissions,observations,resolutions}:{expectedContexts:TeachingUpdateContext[];submissions:TeachingUpdateSubmission[];observations:AttendanceObservation[];resolutions:AttendanceConflictContext[]}){return{...summarizeTeachingUpdates(expectedContexts,submissions),unresolvedAttendanceConflicts:countUnresolvedAttendanceConflicts(observations,resolutions)};}
