import 'server-only';
import {createServerSupabaseClient} from '@/lib/supabase/server';
import type {ClassSummary} from './class.types';

type ClassRow={id:string;name_en:string;name_ar:string|null;is_active:boolean;class_enrollments:Array<{ends_on:string|null}>;class_subjects:Array<{id:string;is_active:boolean;subjects:{id:string;name_en:string;name_ar:string|null}|null;subject_groups:Array<{id:string;name_en:string;name_ar:string|null;is_active:boolean}>;default_group_id:string|null;teaching_assignments:Array<{id:string}>}>};
const select='id,name_en,name_ar,is_active,class_enrollments(ends_on),class_subjects(id,is_active,default_group_id,subjects(id,name_en,name_ar),subject_groups(id,name_en,name_ar,is_active),teaching_assignments(id))';
function map(row:ClassRow):ClassSummary&{isActive:boolean}{return{id:row.id,nameEn:row.name_en,nameAr:row.name_ar,isActive:row.is_active,activeStudentCount:row.class_enrollments.filter(x=>x.ends_on===null).length,subjects:row.class_subjects.filter(x=>x.is_active&&x.subjects).map(x=>({id:x.id,subject:{id:x.subjects!.id,nameEn:x.subjects!.name_en,nameAr:x.subjects!.name_ar},groups:x.subject_groups.filter(g=>g.is_active).map(g=>({id:g.id,nameEn:g.name_en,nameAr:g.name_ar,isDefault:g.id===x.default_group_id})),teacherCount:x.teaching_assignments.length}))}}
export async function listClasses(schoolId:string,includeArchived=true){const db=await createServerSupabaseClient();let q=db.from('classes').select(select).eq('school_id',schoolId).order('name_en');if(!includeArchived)q=q.eq('is_active',true);const{data,error}=await q;if(error)throw error;return(data as unknown as ClassRow[]).map(map)}
export async function getClass(schoolId:string,id:string){const db=await createServerSupabaseClient();const{data,error}=await db.from('classes').select(select).eq('school_id',schoolId).eq('id',id).maybeSingle();if(error)throw error;return data?map(data as unknown as ClassRow):null}
export async function createClass(schoolId:string,input:{nameEn:string;nameAr:string|null}){const db=await createServerSupabaseClient();const{data,error}=await db.from('classes').insert({school_id:schoolId,name_en:input.nameEn,name_ar:input.nameAr}).select('id').single();if(error)throw error;return data.id as string}
export async function updateClass(schoolId:string,id:string,input:{nameEn:string;nameAr:string|null}){const db=await createServerSupabaseClient();const{error}=await db.from('classes').update({name_en:input.nameEn,name_ar:input.nameAr}).eq('school_id',schoolId).eq('id',id);if(error)throw error}
export async function setClassActive(schoolId:string,id:string,isActive:boolean){const db=await createServerSupabaseClient();const{error}=await db.from('classes').update({is_active:isActive}).eq('school_id',schoolId).eq('id',id);if(error)throw error}
export async function addSubject(schoolId:string,classId:string,input:{nameEn:string;nameAr:string|null}){const db=await createServerSupabaseClient();const{data:foundSubject,error}=await db.from('subjects').select('id').eq('school_id',schoolId).eq('name_en',input.nameEn).maybeSingle();if(error)throw error;let subject=foundSubject;if(!subject){const result=await db.from('subjects').insert({school_id:schoolId,name_en:input.nameEn,name_ar:input.nameAr}).select('id').single();if(result.error)throw result.error;subject=result.data}const result=await db.from('class_subjects').insert({school_id:schoolId,class_id:classId,subject_id:subject.id});if(result.error)throw result.error}
export async function addGroup(classSubjectId:string,input:{nameEn:string;nameAr:string|null}){const db=await createServerSupabaseClient();const{error}=await db.rpc('create_subject_group',{p_class_subject_id:classSubjectId,p_name_en:input.nameEn,p_name_ar:input.nameAr??''});if(error)throw error}
export async function setDefaultGroup(schoolId:string,classSubjectId:string,groupId:string){const db=await createServerSupabaseClient();const{error}=await db.from('class_subjects').update({default_group_id:groupId}).eq('school_id',schoolId).eq('id',classSubjectId);if(error)throw error}
export async function listAssignmentOptions(schoolId:string){const db=await createServerSupabaseClient();const{data,error}=await db.from('profiles').select('id,display_name').eq('school_id',schoolId).eq('is_active',true).in('role',['ADMIN','TEACHER']).order('display_name');if(error)throw error;return data.map(x=>({id:x.id as string,name:x.display_name as string}))}
export async function assignTeacher(schoolId:string,input:{teacherId:string;classSubjectId:string;groupId:string|null;startsOn:string}){const db=await createServerSupabaseClient();const{error}=await db.from('teaching_assignments').insert({school_id:schoolId,teacher_profile_id:input.teacherId,class_subject_id:input.classSubjectId,subject_group_id:input.groupId,starts_on:input.startsOn});if(error)throw error}
