'use server';
import {revalidatePath} from 'next/cache';import {redirect} from 'next/navigation';import {z} from 'zod';import {isLocale} from '@/i18n/config';import {requireProfile} from '@/lib/auth/require-profile';import {databaseUuid} from '@/lib/validation/fields';import {classSchema,subjectGroupSchema,subjectSchema,teachingAssignmentSchema} from './class.schemas';import * as repo from './class.repository';
function locale(data:FormData){const v=String(data.get('locale')??'en');return isLocale(v)?v:'en'}
export async function createClassAction(data:FormData){const l=locale(data),p=await requireProfile(l,'ADMIN');const parsed=classSchema.safeParse({nameEn:data.get('nameEn'),nameAr:data.get('nameAr')});if(!parsed.success)return;const id=await repo.createClass(p.schoolId,parsed.data);redirect(`/${l}/classes/${id}`)}
export async function updateClassAction(data:FormData){const l=locale(data),p=await requireProfile(l,'ADMIN');const parsed=classSchema.extend({id:databaseUuid}).safeParse({id:data.get('id'),nameEn:data.get('nameEn'),nameAr:data.get('nameAr')});if(!parsed.success)return;await repo.updateClass(p.schoolId,parsed.data.id,parsed.data);revalidatePath(`/${l}/classes/${parsed.data.id}`)}
export async function setClassActiveAction(data:FormData){const l=locale(data),p=await requireProfile(l,'ADMIN');const parsed=z.object({id:databaseUuid,active:z.enum(['true','false'])}).safeParse({id:data.get('id'),active:data.get('active')});if(!parsed.success)return;await repo.setClassActive(p.schoolId,parsed.data.id,parsed.data.active==='true');revalidatePath(`/${l}/classes`)}
export async function addSubjectAction(data:FormData){const l=locale(data),p=await requireProfile(l,'ADMIN');const parsed=subjectSchema.extend({classId:databaseUuid}).safeParse({classId:data.get('classId'),nameEn:data.get('nameEn'),nameAr:data.get('nameAr')});if(!parsed.success)return;await repo.addSubject(p.schoolId,parsed.data.classId,parsed.data);revalidatePath(`/${l}/classes/${parsed.data.classId}`)}
export async function addGroupAction(data:FormData){const l=locale(data);await requireProfile(l,'ADMIN');const parsed=subjectGroupSchema.extend({classId:databaseUuid}).safeParse({classId:data.get('classId'),classSubjectId:data.get('classSubjectId'),nameEn:data.get('nameEn'),nameAr:data.get('nameAr')});if(!parsed.success)return;await repo.addGroup(parsed.data.classSubjectId,parsed.data);revalidatePath(`/${l}/classes/${parsed.data.classId}`)}
export async function setDefaultGroupAction(data:FormData){const l=locale(data),p=await requireProfile(l,'ADMIN');const parsed=z.object({classId:databaseUuid,classSubjectId:databaseUuid,groupId:databaseUuid}).safeParse(Object.fromEntries(data));if(!parsed.success)return;await repo.setDefaultGroup(p.schoolId,parsed.data.classSubjectId,parsed.data.groupId);revalidatePath(`/${l}/classes/${parsed.data.classId}`)}
export async function assignTeacherAction(data:FormData){const l=locale(data),p=await requireProfile(l,'ADMIN');const parsed=teachingAssignmentSchema.extend({classId:databaseUuid}).safeParse({classId:data.get('classId'),teacherProfileId:data.get('teacherProfileId'),classSubjectId:data.get('classSubjectId'),subjectGroupId:String(data.get('subjectGroupId')??'')||null,startsOn:data.get('startsOn')});if(!parsed.success)return;await repo.assignTeacher(p.schoolId,{teacherId:parsed.data.teacherProfileId,classSubjectId:parsed.data.classSubjectId,groupId:parsed.data.subjectGroupId,startsOn:parsed.data.startsOn});revalidatePath(`/${l}/classes/${parsed.data.classId}`)}
