-- Academic rows are school isolated; admins mutate, assigned teachers receive narrow reads.
do $$ declare t text; begin foreach t in array array['classes','subjects','class_subjects','subject_groups','class_enrollments','subject_exclusions','subject_group_memberships','teaching_assignments'] loop execute format('alter table public.%I enable row level security',t); execute format('alter table public.%I force row level security',t); execute format('create policy %I on public.%I for all to authenticated using (school_id=public.current_school_id() and public.is_admin()) with check (school_id=public.current_school_id() and public.is_admin())',t||'_admin',t); end loop; end $$;
create policy classes_teacher_read on public.classes for select to authenticated using(school_id=public.current_school_id() and exists(select 1 from public.class_subjects cs join public.teaching_assignments ta on ta.class_subject_id=cs.id and ta.school_id=cs.school_id where cs.class_id=classes.id and ta.teacher_profile_id=public.current_profile_id() and current_date between ta.starts_on and coalesce(ta.ends_on,'infinity')));
create policy subjects_teacher_read on public.subjects for select to authenticated using(school_id=public.current_school_id() and exists(select 1 from public.class_subjects cs join public.teaching_assignments ta on ta.class_subject_id=cs.id and ta.school_id=cs.school_id where cs.subject_id=subjects.id and ta.teacher_profile_id=public.current_profile_id() and current_date between ta.starts_on and coalesce(ta.ends_on,'infinity')));
create policy class_subjects_teacher_read on public.class_subjects for select to authenticated using(school_id=public.current_school_id() and public.teacher_can_teach_context(public.current_profile_id(),id,null,current_date));
create policy subject_groups_teacher_read on public.subject_groups for select to authenticated using(school_id=public.current_school_id() and public.teacher_can_teach_context(public.current_profile_id(),class_subject_id,id,current_date));
create policy teaching_assignments_self_read on public.teaching_assignments for select to authenticated using(school_id=public.current_school_id() and teacher_profile_id=public.current_profile_id());
create policy enrollments_teacher_read on public.class_enrollments for select to authenticated using(school_id=public.current_school_id() and exists(select 1 from public.class_subjects cs where cs.class_id=class_enrollments.class_id and public.teacher_can_teach_context(public.current_profile_id(),cs.id,null,current_date)));
create policy exclusions_teacher_read on public.subject_exclusions for select to authenticated using(school_id=public.current_school_id() and public.teacher_can_teach_context(public.current_profile_id(),class_subject_id,null,current_date));
create policy memberships_teacher_read on public.subject_group_memberships for select to authenticated using(school_id=public.current_school_id() and public.teacher_can_teach_context(public.current_profile_id(),class_subject_id,subject_group_id,current_date));
