create type public.report_workflow_status as enum('DRAFT','REVIEW','FINALIZED','SENT');
create table public.report_batches(id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id), period_start date not null, period_end date not null, scope_type text not null check(scope_type in('CLASS','SUBJECT','GROUP')), scope_id uuid not null, status public.report_workflow_status not null default 'DRAFT', created_by uuid not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(school_id,id), foreign key(school_id,created_by) references public.profiles(school_id,id), check(period_end>=period_start));
create table public.report_approvals(id uuid primary key default gen_random_uuid(), school_id uuid not null, batch_id uuid not null, class_subject_id uuid not null, student_id uuid, progress_en text, progress_ar text, performance public.performance_level, comment_en text, comment_ar text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(school_id,id), foreign key(school_id,batch_id) references public.report_batches(school_id,id), foreign key(school_id,class_subject_id) references public.class_subjects(school_id,id), foreign key(school_id,student_id) references public.students(school_id,id));
alter table public.reports drop constraint reports_school_id_student_id_period_start_period_end_language_key;
alter table public.reports add column snapshot_version integer not null default 1, add column batch_id uuid, add column revision integer not null default 1, add column finalized_at timestamptz, add constraint reports_batch_fk foreign key(school_id,batch_id) references public.report_batches(school_id,id);
create unique index reports_revision_identity on public.reports(school_id,student_id,period_start,period_end,language,revision);
alter table public.report_batches enable row level security; alter table public.report_batches force row level security; alter table public.report_approvals enable row level security; alter table public.report_approvals force row level security;
create policy report_batches_admin on public.report_batches for all to authenticated using(school_id=public.current_school_id() and public.is_admin()) with check(school_id=public.current_school_id() and public.is_admin()); create policy report_approvals_admin on public.report_approvals for all to authenticated using(school_id=public.current_school_id() and public.is_admin()) with check(school_id=public.current_school_id() and public.is_admin());
create function public.protect_finalized_report() returns trigger language plpgsql set search_path='' as $$ begin if old.finalized_at is not null and new is distinct from old then raise exception 'finalized reports are immutable'; end if; return new; end $$; create trigger reports_immutable before update on public.reports for each row execute function public.protect_finalized_report();
